"""Initial setup for Supabase

Revision ID: c53743cd0a43
Revises: 
Create Date: 2026-02-12 11:18:07.765137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c53743cd0a43"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "short_urls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("short_code", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("click_count", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_short_urls_short_code"), "short_urls", ["short_code"], unique=True)
    op.create_table(
        "analytics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("short_code_id", sa.UUID(), nullable=False),
        sa.Column(
            "clicked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("os", sa.String(length=50), nullable=True),
        sa.Column("browser", sa.String(length=50), nullable=True),
        sa.Column("referrer", sa.String(length=2000), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["short_code_id"],
            ["short_urls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_short_url_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("short_url_id", sa.UUID(), nullable=False),
        sa.Column("date_of_stat", sa.Date(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("unique_visitors", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["short_url_id"], ["short_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_short_url_stats_date_of_stat"),
        "daily_short_url_stats",
        ["date_of_stat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_short_url_stats_short_url_id"),
        "daily_short_url_stats",
        ["short_url_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_short_url_stats_short_url_id"), table_name="daily_short_url_stats")
    op.drop_index(op.f("ix_daily_short_url_stats_date_of_stat"), table_name="daily_short_url_stats")
    op.drop_table("daily_short_url_stats")
    op.drop_table("analytics")
    op.drop_index(op.f("ix_short_urls_short_code"), table_name="short_urls")
    op.drop_table("short_urls")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
